/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'minecraft-pi'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

union $F85E194B51CBDC38F209555F4162D10C;
union $781B27F37A2DA3C5D0084E69F313DC7D;
struct $6ECA53571B8FCC125A3088582131FB6E;

/* 1 */
struct __attribute__((aligned(4))) Elf32_Sym
{
  unsigned __int32 st_name;
  unsigned __int32 st_value;
  unsigned __int32 st_size;
  unsigned __int8 st_info;
  unsigned __int8 st_other;
  unsigned __int16 st_shndx;
};

/* 2 */
struct Elf32_Rel
{
  unsigned __int32 r_offset;
  unsigned __int32 r_info;
};

/* 4 */
union Elf32_Dyn::$A263394DDF3EC2D4B1B8448EDD30E249
{
  unsigned __int32 d_val;
  unsigned __int32 d_ptr;
};

/* 3 */
struct Elf32_Dyn
{
  __int32 d_tag;
  union Elf32_Dyn::$A263394DDF3EC2D4B1B8448EDD30E249 d_un;
};

/* 5 */
struct __attribute__((aligned(4))) Elf32_Verneed
{
  unsigned __int16 vn_version;
  unsigned __int16 vn_cnt;
  unsigned __int32 vn_file;
  unsigned __int32 vn_aux;
  unsigned __int32 vn_next;
};

/* 6 */
struct __attribute__((aligned(4))) Elf32_Vernaux
{
  unsigned __int32 vna_hash;
  unsigned __int16 vna_flags;
  unsigned __int16 vna_other;
  unsigned __int32 vna_name;
  unsigned __int32 vna_next;
};

/* 7 */
typedef signed __int32 _Unwind_Sword;

/* 8 */
typedef unsigned __int32 _Unwind_Ptr;

/* 9 */
typedef unsigned __int32 _Unwind_Internal_Ptr;

/* 10 */
typedef unsigned __int32 _Unwind_Word;

/* 11 */
typedef int _Unwind_Action;

/* 12 */
typedef unsigned __int64 _Unwind_Exception_Class;

/* 13 */
enum $BDF88968CAE1EA74E42809B9AE857E7C
{
  _URC_NO_REASON = 0x0,
  _URC_FOREIGN_EXCEPTION_CAUGHT = 0x1,
  _URC_FATAL_PHASE2_ERROR = 0x2,
  _URC_FATAL_PHASE1_ERROR = 0x3,
  _URC_NORMAL_STOP = 0x4,
  _URC_END_OF_STACK = 0x5,
  _URC_HANDLER_FOUND = 0x6,
  _URC_INSTALL_CONTEXT = 0x7,
  _URC_CONTINUE_UNWIND = 0x8,
};

/* 14 */
typedef enum $BDF88968CAE1EA74E42809B9AE857E7C _Unwind_Reason_Code;

/* 15 */
struct _Unwind_Exception;

/* 16 */
struct _Unwind_Context;

/* 17 */
typedef void (__cdecl *_Unwind_Exception_Cleanup_Fn)(_Unwind_Reason_Code, struct _Unwind_Exception *);

/* 18 */
typedef _Unwind_Reason_Code (__cdecl *_Unwind_Personality_Fn)(int, _Unwind_Action, _Unwind_Exception_Class, struct _Unwind_Exception *, struct _Unwind_Context *);

/* 19 */
typedef _Unwind_Reason_Code (__cdecl *_Unwind_Stop_Fn)(int, _Unwind_Action, _Unwind_Exception_Class, struct _Unwind_Exception *, struct _Unwind_Context *, void *);

/* 20 */
typedef _Unwind_Sword __guard;

/* 22 */
typedef int __time_t;

/* 23 */
typedef int __suseconds_t;

/* 21 */
struct timeval
{
  __time_t tv_sec;
  __suseconds_t tv_usec;
};

/* 24 */
typedef $F85E194B51CBDC38F209555F4162D10C pthread_mutex_t;

/* 29 */
struct __pthread_internal_slist
{
  __pthread_internal_slist *__next;
};

/* 28 */
typedef __pthread_internal_slist __pthread_slist_t;

/* 27 */
union $::__pthread_mutex_s::$30DFB618E49C377A3D62C6584A4CBE95
{
  int __spins;
  __pthread_slist_t __list;
};

/* 26 */
struct $F85E194B51CBDC38F209555F4162D10C::__pthread_mutex_s
{
  int __lock;
  unsigned int __count;
  int __owner;
  int __kind;
  unsigned int __nusers;
  union
  {
    int __spins;
    __pthread_slist_t __list;
  };
};

/* 25 */
union $F85E194B51CBDC38F209555F4162D10C
{
  $F85E194B51CBDC38F209555F4162D10C::__pthread_mutex_s __data;
  char __size[24];
  int __align;
};

/* 30 */
struct timespec
{
  __time_t tv_sec;
  int tv_nsec;
};

/* 31 */
typedef $781B27F37A2DA3C5D0084E69F313DC7D pthread_attr_t;

/* 32 */
union $781B27F37A2DA3C5D0084E69F313DC7D
{
  char __size[36];
  int __align;
};

/* 33 */
struct sched_param
{
  int __sched_priority;
};

/* 35 */
typedef unsigned __int16 sa_family_t;

/* 34 */
struct sockaddr
{
  sa_family_t sa_family;
  char sa_data[14];
};

/* 36 */
typedef $6ECA53571B8FCC125A3088582131FB6E fd_set;

/* 38 */
typedef int __fd_mask;

/* 37 */
struct $6ECA53571B8FCC125A3088582131FB6E
{
  __fd_mask __fds_bits[32];
};

/* 39 */
struct RakNet::RakNetRandom;

/* 40 */
struct RakNet::SimpleMutex;

/* 41 */
struct std::string;

/* 42 */
struct std::nothrow_t;

/* 43 */
struct std::__detail::_List_node_base;

/* 44 */
struct std::istream;

/* 45 */
struct RakNet;

/* 46 */
struct RakStringCleanup;

